#
# Module manifest for module 'HPEStoragePowerShellToolkit'
#
# Generated by: Hewlett Packard Enterprise Development LP
#
# Generated on: 10-06-2021
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '3.1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '46a7e8f6-729c-45d0-b979-96c684fb28fe'

# Author of this module
Author = 'Hewlett Packard Enterprise Development LP'

# Company or vendor of this module
CompanyName = 'Hewlett Packard Enterprise Development LP'

# Copyright statement for this module
Copyright = '© 2020,2021 Hewlett Packard Enterprise Development LP'

# Description of the functionality provided by this module
Description = 'HPE Alletra 9000 and Primera and 3PAR PowerShell Toolkit provides storage administrators the convenience of managing HPE Alletra 9000 and HPE Primera and HPE 3PAR Storage Systems from a Microsoft Windows PowerShell environment.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('.\GLOBAL\VS-Functions.psm1', 
               '.\GLOBAL\Logger.psm1', 
               '.\CLI\AdaptiveOptimization.psm1', 
               '.\CLI\ConfigWebServicesAPI.psm1', 
               '.\CLI\CPGManagement.psm1', 
               '.\CLI\DiskEnclosureManagement.psm1', 
               '.\CLI\DomainManagement.psm1', 
               '.\CLI\FilePersonaManagement.psm1', 
               '.\CLI\Flashcache.psm1', 
               '.\CLI\HealthAndAlertManagement.psm1', 
               '.\CLI\HostManagement.psm1', 
               '.\CLI\Internal.psm1', 
               '.\CLI\InventoryManagement.psm1', 
               '.\CLI\MaintenanceMode.psm1', 
               '.\CLI\NodeSubsystemManagement.psm1', 
               '.\CLI\PerformanceManagement.psm1', 
               '.\CLI\Replication.psm1', 
               '.\CLI\ServiceCommands.psm1', 
               '.\CLI\SnapShotManagement.psm1', 
               '.\CLI\Sparing.psm1', 
               '.\CLI\SystemManager.psm1', 
               '.\CLI\SystemReporter.psm1', 
               '.\CLI\TaskManagement.psm1', 
			   '.\CLI\CimManagement.psm1', 
               '.\CLI\UserManagement.psm1', 
               '.\CLI\Vasa.psm1', 
               '.\CLI\StorageFederation.psm1', 
               '.\CLI\VirtualVolumeManagement.psm1', 
               '.\CLI\vLunManagement.psm1', 
               '.\WSAPI\AoConfigurationInformation.psm1', 
               '.\WSAPI\AvailableSpace.psm1', 
               '.\WSAPI\CopyOperations.psm1', 
               '.\WSAPI\CpgManagement.psm1', 
               '.\WSAPI\FilePersona.psm1', 
               '.\WSAPI\FlashCacheOperations.psm1', 
               '.\WSAPI\HostManagement.psm1', 
               '.\WSAPI\HostSetsAndVirtualVolumeSets.psm1', 
               '.\WSAPI\PortsAndSwitches.psm1', 
               '.\WSAPI\RemoteCopy.psm1', 
               '.\WSAPI\SessionKeysAndWsapiSystemAccess.psm1', 
               '.\WSAPI\StorageVolumes.psm1', 
               '.\WSAPI\SystemEvents.psm1', 
               '.\WSAPI\SystemInformationQueriesAndManagement.psm1', 
               '.\WSAPI\SystemReporter.psm1', 
               '.\WSAPI\VirtualLUNs.psm1', 
               '.\WSAPI\WsapiUserAndRoleInformation.psm1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'HPE Alletra PS Cmdlets', 'HPE Primera PS Cmdlets', 'HPE 3PAR PS Cmdlets', 'HPE Alletra CLI', 'HPE Primera CLI', 
               'HPE 3PAR CLI', 'HPE Alletra WSAPI', 'HPE Primera WSAPI', 'HPE 3PAR WSAPI', '3PAR PSTK', 
               'PRIMERA PSTK', 'ALLETRA PSTK'

        # A URL to the license for this module.
        # LicenseUri = 'https://github.com/HewlettPackard/hpe3par_pstoolkit/blob/master/LICENSE.txt'

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}

